### ISSUE TITLE
Failed to load the python package

### ISSUE THREAD

**Issue by svlasov** [rgbkrk/atom-python#12]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [python](https://github.com/rgbkrk/atom-python) package, v0.5.1
### Stack Trace

Failed to load the python package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/user/.atom/packages/python/lib/python-view.coffee:4:199)
    at /Users/user/.atom/packages/python/lib/python-view.coffee:9:5
    at Object.<anonymous> (/Users/user/.atom/packages/python/lib/python-view.coffee:70:5)
    at Object.<anonymous> (/Users/user/.atom/packages/python/lib/python-view.coffee:72:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "useReactEditor": false,
    "disabledPackages": [
      "term"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-python-debugger, v0.2.2
atom-terminal, v0.7.0
language-docker, v1.1.3
linter-python-pep8, v0.2.0
polymer-snippets, v1.1.2
python, v0.5.1
term2, v0.9.4

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
**Please use [the script package](https://atom.io/packages/script) instead.**

Script supports everything this package did and more, including virtualenvs! Please switch.
